### ISSUE TITLE
[client/catapult] Failure_LockSecret_Hash_Already_Exists Failure_Consumer_Remote_Chain_Unlinked

### ISSUE THREAD

**Issue by Jacky-29** [symbol/symbol#1379]
### System Information

- **REST Version && Client Version :
{
    "serverInfo": {
        "restVersion": "2.4.3",
        "deployment": {
            "deploymentTool": "symbol-bootstrap",
            "deploymentToolVersion": "1.1.10",
            "lastUpdatedDate": "2024-11-25"
        }
    }
}
- **Operating System:** Linux Ubuntu
- **Installed With:** Bootstrap
- **Are you fully synchronized?** No
- **Did you try to restart your node?** Yes

#### Description

> Unable to synchronize to the latest height,  alarm: Failure_Consumer_Remote_Chain_Unlinked, Failure_LockSecret_Hash_Already_Exists
/node/storage response:
{
    "numBlocks": 3193302,
    "numTransactions": 10897271,
    "numAccounts": 259235,
    "database": {
        "numIndexes": 76,
        "numObjects": 17958703,
        "dataSize": 17410171425,
        "indexSize": 1687896064,
        "storageSize": 10431188992
    }
}

#### Steps to Reproduce
> [1.] symbol-bootstrap config -p mainnet -a api
> [2.] symbol-bootstrap compose
> [3.] sudo symbol-bootstrap run

#### Logs
node            | 2024-11-28 02:08:49.113034 0x00007fc3b7fff640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3191538 - 3191897) 
node            | 2024-11-28 02:08:49.930026 0x00007fc3b5ffb640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3191898 - 3192257) 
node            | 2024-11-28 02:08:50.743596 0x00007fc395ffb640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3192258 - 3192617) 
node            | 2024-11-28 02:08:51.558792 0x00007fc3967fc640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3192618 - 3192977) 
node            | 2024-11-28 02:08:52.371377 0x00007fc3977fe640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3192978 - 3193337) 
node            | 2024-11-28 02:08:52.371493 0x00007fc3977fe640: <info> (chain::RemoteApiForwarder.h@69) completed 'synchronizer task' (Allnodes841 @ xym841.allnodes.me:7900) with result Success 
node            | 2024-11-28 02:08:55.682548 0x00007fc3967fc640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3193338 - 3193697) 
node            | 2024-11-28 02:08:55.682605 0x00007fc3967fc640: <info> (chain::RemoteApiForwarder.h@69) completed 'synchronizer task' (!!Mon-Sat_Fee_Free/policy:age/Max:200!! @ symbol-node.harvest-xym.com:7900) with result Success 
node            | 2024-11-28 02:08:57.893608 0x00007fc30a7fc640: <warning> (consumers::BlockchainProcessor.cpp@140) batch processing of block 3191538 failed with Failure_LockSecret_Hash_Already_Exists 
node            | 2024-11-28 02:08:57.893639 0x00007fc30a7fc640: <warning> (consumers::BlockchainSyncConsumer.cpp@268) processing of peer chain failed with Failure_LockSecret_Hash_Already_Exists 
node            | 2024-11-28 02:08:57.910891 0x00007fc309ffb640: <info> (disruptor::ConsumerDispatcher.cpp@44) completing processing of element 8228 (1800 blocks (heights 3191538 - 3193337) [4040FB15] from Remote_Pull with size 10MB 535KB 719B), last consumer is 1 elements behind 
node            | 2024-11-28 02:08:57.910924 0x00007fc309ffb640: <warning> (consumers::ReclaimMemoryInspector.cpp@33) consumer aborted at position 8227 while processing 1800 blocks (heights 3191538 - 3193337) [4040FB15] from Remote_Pull with size 10MB 535KB 719B due to Failure_LockSecret_Hash_Already_Exists 
node            | 2024-11-28 02:08:57.913596 0x00007fc309ffb640: <info> (disruptor::ConsumerDispatcher.cpp@44) completing processing of element 8229 (360 blocks (heights 3193338 - 3193697) [9D9BCBF9] from Remote_Pull with size 143KB 80B), last consumer is 0 elements behind 
node            | 2024-11-28 02:08:57.913618 0x00007fc309ffb640: <warning> (consumers::ReclaimMemoryInspector.cpp@33) consumer aborted at position 8228 while processing 360 blocks (heights 3193338 - 3193697) [9D9BCBF9] from Remote_Pull with size 143KB 80B due to Failure_Consumer_Remote_Chain_Unlinked 
db              | {"t":{"$date":"2024-11-28T02:08:58.613+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":"[1732759738:613102][1:0x7f0e5e2d9700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 49411, snapshot max: 49411 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 5549914"}}
node            | 2024-11-28 02:09:11.730917 0x00007fc3977fe640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3191538 - 3191897) 
node            | 2024-11-28 02:09:12.522855 0x00007fc3c56c6640: <info> (chain::ChainSynchronizer.cpp@217) peer returned 360 blocks (heights 3191898 - 3192257)

**Comment by Wayonb** [comment]
Please upgrade to the latest release of catapult - https://x.com/thesymbolchain/status/1776647958718767608

**Comment by Jacky-29** [comment]
How to upgrade to the latest version of catapult? Try symbol-bootstrap start --upgrade -c ./target/presets.yml but it does not work. Maybe change target/docker/docker-compose.yml  config image: symbolplatform/symbol-server:gcc-1.0.3.6 to symbolplatform/symbol-server:gcc-1.0.3.7?

**Comment by Jacky-29** [comment]
> Please upgrade to the latest release of catapult - https://x.com/thesymbolchain/status/1776647958718767608
How to upgrade to the latest version of catapult? Try symbol-bootstrap start --upgrade -c ./target/presets.yml but it does not work. Maybe change target/docker/docker-compose.yml config image: symbolplatform/symbol-server:gcc-1.0.3.6 to symbolplatform/symbol-server:gcc-1.0.3.7?

**Comment by Wayonb** [comment]
Hi, to install the latest for symbol-bootstrap https://x.com/thesymbolchain/status/1776716950896594993

1. git clone https://github.com/symbol/symbol-bootstrap
2. cd symbol-bootstrap
3. sudo npm install -g

**Comment by Jacky-29** [comment]
Yes, it is worked, ths
