### ISSUE TITLE
[sdk/python] sending transaction - error for unordered mosaics array

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/symbol#205]
When a mosaic array is not ordered by mosaic_id when constructing a transaction we get the error: "array passed to write array is not sorted". SDK should handle sorting and not require to sort it by the developer which is using SDK.

Example code causing the error:
```
facade = SymbolFacade('mainnet')
transaction = facade.transaction_factory.create({
        "type":"transfer_transaction",
        "signer_public_key":key_pair.public_key,
        "deadline":get_deadline(),
        "recipient_address":to_address,
        "mosaics":[
            {'mosaic_id': 0x6BED913FA20223F8, 'amount': 1},
            {'mosaic_id': 0x394832C219D2B952, 'amount': 2} 
        ]
})
transaction.fee.value = transaction.size * 100
signature = sign_transaction(facade,key_pair,transaction)
```
Result:
Error: `array passed to write array is not sorted`

Expected result:
SDK should handle sorting of mosaic array internally (if it's required to serialize sorted).

Used SDK version: 3.0.3

The corresponding issue for JS SDK: #206

**Comment by gimre-xymcity** [comment]
auto-sorting for create() is now default behavior, py sdk 3.0.4

**Comment by cryptoBeliever** [comment]
It was tested on the dev branch. Works correctly. Example transaction:

```
transfer = facade.transaction_factory.create({
	'type': 'transfer_transaction_v1',
	'signer_public_key': alicePubkey,
	'recipient_address': bobAddress,
	'deadline': deadline,
	'fee': 100000,
	'mosaics': [
		{
          'mosaic_id': 0x3B6C1884BB157E22,
          'amount': 100
        },
        {
          'mosaic_id': 0x11A883250997A39A,
          'amount': 100
        }
	]
})
```

https://testnet.symbol.fyi/transactions/6702A3E6BA6F440B3F8016D81CD2FB4A8381615D2B0C9D15F6C82E8BD8BD98DD
