### ISSUE TITLE
[sdk/javascript] Export converter utils method.

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/symbol#215]
## Current Behaviour

In some projects, it required utils converter method `uint8ToHex` and `hexToUint8`.
rather than re-write the function, I believe it will be good to export it from the SDK.

https://github.com/symbol/symbol/blob/ab98b8c37daa93d1a5620722d10457a27d0156bd/sdk/javascript/src/utils/converter.js#L64

https://github.com/symbol/symbol/blob/ab98b8c37daa93d1a5620722d10457a27d0156bd/sdk/javascript/src/utils/converter.js#L80

## Expected Behaviour
We can use the it directly import from SDK without rewrite.
example `const { uint8ToHex, hexToUint8 } = require('symbol-sdk').converter;`

**Comment by Jaguar0625** [comment]
@AnthonyLaw - some of your usages look incorrect
`new NemFacade.Address(hexStringToByte(props.address)`
should be same as
