### ISSUE TITLE
[sdk/javascript] Replace js-sha3

### ISSUE THREAD

**Issue by haryu703** [symbol/symbol#221]
## Current Behaviour
Original: https://github.com/symbol/symbol-sdk-typescript-javascript/issues/622
js-sha3 in dependencies looks no longer maintained.
Note that current implementation doesn't have original issue so this issue is just improvement.

## Expected Behaviour
- Same behaviour as current implementation.
- Independent of js-sha3.

**Comment by Jaguar0625** [comment]
Merged in ecb8db522eec25735378063a0a535270493681a2. Good job 👍 .
