### ISSUE TITLE
[sdk/python] Transfer transaction - support for message types

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/symbol#229]
## Current Behaviour

Old SDKs message specification defined four types of messages:
- Plain Message (prefix 0)
- Encrypted Message (prefix 1)
- Persistent Delegated Message transaction (prefix 254)
- Raw Message (no prefix or not recognized prefix)

Currently, the SDK user (developer) has only the option to put the message as raw text when creating the transfer transaction object. So SDK user has to:
- remember (when sending and when reading from API transactions) which prefix is for which transaction type and how to decode messages
- implement encryption and decryption of messages (in case of encrypted messages)
- implement persistent delegating message creation

## Expected Behaviour

It's desired that SDK users be released from the obligation to remember the specification for various types of messages.
For SDK developers would be very helpful if:
- he could create objects representing a specific message type (constructor/factory methods)
- when reading transactions from API provide a way to read messages without knowing the specification e.g. wrapping messages using a typed message object.

Corresponding issue for JS SDK: #228

**Comment by gimre-xymcity** [comment]
this is currently done via MessageEncoder object,
however, currently in case of NEM it will throw an error if it's instantiated on non-encrypted message type.
additionally try_decode/tryDecocde might throw in some cases

**Comment by cryptoBeliever** [comment]
Encrypting and decrypting message work correctly :heavy_check_mark:
