### ISSUE TITLE
[sdk/javascript] Metadata - provide util to calculate delta (xor) value and delta length

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/symbol#297]
## Current Behaviour

Previous SDK when constructing Metadata (Namespace/Mosaic/Account) Transaction automatically calculated delta value and length based on on-chain metadata value fetched during Transaction creation. 

New SDK is not doing network communication but would be nice to provide a helper or other way (additional field?) to provide previous value (which the user has to manually fetch from the network) and new value. It would calculate the correct delta value and delta length to put into the transaction.

## Expected Behaviour

Provide util/helper or a way to pass previous value during Metadata Transaction creation. Based on that we could calculate:
- value (delta)
- value size
- value size delta

Python issue: #298

**Comment by gimre-xymcity** [comment]
@Jaguar0625 can we close this one and #298 ?

**Comment by gimre-xymcity** [comment]
part of js sdk 3.0.4
