### ISSUE TITLE
[sdk/python] Metadata - provide util to calculate delta (xor) value and delta length

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/symbol#298]
## Current Behaviour

Previous SDK when constructing Metadata (Namespace/Mosaic/Account) Transaction automatically calculated delta value and length based on on-chain metadata value fetched during Transaction creation. 

New SDK is not doing network communication but would be nice to provide a helper or other way (additional field?) to provide previous value (which the user has to manually fetch from the network) and new value. It would calculate the correct delta value and delta length to put into the transaction.

## Expected Behaviour

Provide util/helper or a way to pass previous value during Metadata Transaction creation. Based on that we could calculate:
- value (delta)
- value size
- value size delta

JS issue: #297

**Comment by gimre-xymcity** [comment]
part of py sdk 3.0.4

**Comment by cryptoBeliever** [comment]
Works correctly. Tried on dev branch:

```
old_value = b'test value'
new_value = b'test value _ 123 :)'
value_delta = metadata_update_value(old_value, new_value)

embedded_transactions = []

metadata = facade.transaction_factory.create_embedded({
	'type': 'account_metadata_transaction_v1',
	'signer_public_key': alicePubkey,
	'target_address': aliceAddress,
	'scoped_metadata_key': 2,
	'value': value_delta,
	'value_size_delta': len(new_value) - len(old_value)
})

embedded_transactions.append(metadata)
merkle_hash = facade.hash_embedded_transactions(embedded_transactions)

aggregate_transaction = facade.transaction_factory.create({
	'type': 'aggregate_complete_transaction_v2',
	'signer_public_key': alicePubkey,
	'fee': 100000,
	'deadline': deadline,
	'transactions_hash': merkle_hash,
	'transactions': embedded_transactions
})
```
