### ISSUE TITLE
[catbuffer/parser]  Parsing hash_lock.cat does not output data for factory_type: Transaction.

### ISSUE THREAD

**Issue by xembook** [symbol/symbol#336]
I am processing the yaml file output by catparser into json to create a sdk.
However, in hash_lock.cat, I noticed that the data defining the transaction layout is not output.
Specifically, the data begins with the following key
```
  - type
  factory_type: Transaction
```

I feel that perhaps the apostrophe used in the following line has invalidated subsequent statements.

https://github.com/symbol/symbol/blob/04fc8200a17509fd1e3c4194898f16336a89d04e/catbuffer/schemas/symbol/lock_hash/hash_lock.cats#L18

could you please confirm it. thanks.

**Comment by xembook** [comment]
This is the `factory_type` in transfer.yaml derived from transfer.cat.
https://github.com/xembook/symbol-browserify/blob/3c9e0c5e51882aea5908e3a6631cef9519c57136/catyaml/transfer.yaml#L385

I would like to derive this same thing from hash_lock.cat.
https://github.com/xembook/symbol-browserify/blob/main/catyaml/hash_lock.yaml

**Comment by xembook** [comment]
I found that `secret_lock.cats` also does not output "factory_type: Transaction"

**Comment by Jaguar0625** [comment]
what branch are you using?

**Comment by xembook** [comment]
I am using v3.1.0

like this
```
wget https://github.com/symbol/symbol/archive/refs/tags/catbuffer/parser/v3.1.0.tar.gz
wget https://github.com/symbol/symbol/archive/refs/tags/catbuffer/schemas/v3.1.0.tar.gz
...
pip3 install -r requirements.txt --user
...
python3 -m catparser --schema ../schemas/symbol/lock_hash/hash_lock.cats  --include ../schemas/symbol -o output/hash_lock.yaml
```

**Comment by gimre-xymcity** [comment]
sorry for late answer, seems we've forgotten about this one,

latest `dev` outputs it correctly, I'm not sure if we'll still be providing separate versioning for catbuffer, so easieast version is to grab latest version of catapult itself:
https://github.com/symbol/symbol/archive/refs/tags/client/catapult/v1.0.3.5.tar.gz
