### ISSUE TITLE
[monorepo] Do you have an easy example for deploying an api server in Kubernetes?

### ISSUE THREAD

**Issue by lsdbitrue** [symbol/symbol#389]
symbol-bootstrap is a handy for the most case, but we need to deploy our node in k8s cluster.

it will be great that your team have a helm package for us.

**Comment by Wayonb** [comment]
Yes, I am investigating helm package currently.

**Comment by lsdbitrue** [comment]
@Wayonb I have set up an api server in k8s cluster

and I got an error message from my rest-gateway when I request `/node/info`, do you have any idea about it?

```
{
  message: 'connecting to symbol-node.chainrpc.svc.cluster.local:7900',
  level: 'verbose',
  timestamp: '2022-09-23T09:37:40.005Z'
}
{
  jse_shortmsg: 'connection failed',
  jse_info: {},
  message: 'caught error 503 connection failed',
  body: { code: 'ServiceUnavailable', message: 'connection failed' },
  level: 'error',
  stack: 'ServiceUnavailableError: connection failed\n' +
    '    at Object.createServiceUnavailableError (/app/catapult-rest/rest/src/server/errors.js:56:44)\n' +
    '    at TLSSocket.<anonymous> (/app/catapult-rest/rest/src/connection/catapultConnection.js:27:53)\n' +
    '    at Object.onceWrapper (events.js:421:26)\n' +
    '    at TLSSocket.emit (events.js:326:22)\n' +
    '    at net.js:675:12\n' +
    '    at TCP.done (_tls_wrap.js:568:7)',
  timestamp: '2022-09-23T09:37:40.013Z'
}
```

I have checked the node endpoint with nc

```
nc -w1 -zv symbol-node.chainrpc.svc.cluster.local 7900
symbol-node.chainrpc.svc.cluster.local (172.20.163.214:7900) open
```

config-node.properties

trustedHosts is set to empty to trust all hosts

```
trustedHosts = 
```

[config-node.properties.txt](https://github.com/symbol/symbol/files/9632671/config-node.properties.txt)

the certs are the same between node and rest gateway(BTW, I made a 10 years certificate for the node`)

**Comment by Wayonb** [comment]
Can you give more information on your k8s setup? Is rest in the same pod as catapult client?

**Comment by lsdbitrue** [comment]
> Can you give more information on your k8s setup? Is rest in the same pod as catapult client?

they are two pod.

catapult server and broker are in a pod.

**Comment by lsdbitrue** [comment]
There is no more log to debug, it just told me that connection failed
