### ISSUE TITLE
[client/catapult] can't graceful shutdown broker

### ISSUE THREAD

**Issue by lsdbitrue** [symbol/symbol#390]
### System Information

- **Client Version:** symbolplatform/symbol-server:gcc-10-1.0.3.3
- **REST Version:** 
- **Operating System: Linux
- **Installed With:**  From Source
- **VPS Provider:** AWS
- **Are you fully synchronized?** No
- **Did you try to restart your node?** Yes

#### Steps to Reproduce

start broker and try to kill broker, and broker is just stuck

#### Logs

![Screen Shot 2022-09-22 at 19 09 51](https://user-images.githubusercontent.com/88539015/191731764-2b2e3a9f-f5c2-41d7-90a0-45eac923d9c5.png)

**Comment by Wayonb** [comment]
Are you starting and immediately stopping the broker?
Are you running in a container?

**Comment by lsdbitrue** [comment]
> Are you starting and immediately stopping the broker?

No, about 1 mins after starting


> Are you running in a container?

yes

**Comment by Wayonb** [comment]
If you are running in a container, can you give more information on how you are trying to kill the broker?
