### ISSUE TITLE
[client/catapult] Version and tag.

### ISSUE THREAD

**Issue by eeexception** [symbol/symbol#426]
Hi. According to this release notes:
https://github.com/fboucquez/symbol-bootstrap/releases/tag/v1.1.8
The client 1.0.3.4 was released.
But the latest version in tags and releases in this repository is 1.0.3.3.

So was 1.0.3.4 released or is it still under development?

**Comment by Wayonb** [comment]
It is now release - https://github.com/symbol/symbol/releases/tag/client%2Fcatapult%2Fv1.0.3.4
