### ISSUE TITLE
[sdk/javascript] Having problem to create Nem multisig_transaction_v1

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/symbol#558]
## Current Behaviour

I have an issue creating a `multisig_transaction_v1` (Nem) transaction.

```
const nonVerifiableTransaction = new NonVerifiableClass();
                 ^
TypeError: NonVerifiableClass is not a constructor
```

## Expected Behavior

It should return the transaction payload.

**Comment by gimre-xymcity** [comment]
a) should not be done directly
b) sort of done on catbuffer/non-verifiable-nem-multisig branch

**Comment by gimre-xymcity** [comment]
@AnthonyLaw can you check if linked thing solves, the issue?

This piece shows how to create multisig tx: https://github.com/symbol/symbol/pull/567/files#diff-69df861217ef571e4f5404d77b0ae9f15500c495e2efbb959c3e412dc0bbdf97R176-R190

**Comment by AnthonyLaw** [comment]
> @AnthonyLaw can you check if linked thing solves, the issue?
> 
> This piece shows how to create multisig tx: https://github.com/symbol/symbol/pull/567/files#diff-69df861217ef571e4f5404d77b0ae9f15500c495e2efbb959c3e412dc0bbdf97R176-R190

Nice, it resolved 💯
