### ISSUE TITLE
[sdk/python] The Nem multisig_transaction_v2 is missing in the SDK.

### ISSUE THREAD

**Issue by AnthonyLaw** [symbol/symbol#560]
## Current Behaviour

The current Nem SDK does not support the multisig_transaction_v2 transaction.

## Expected Behavior

The Nem SDK should support the multisig_transaction_v2 transaction.

**Comment by gimre-xymcity** [comment]
Fixed in 57b1685da512272ecbc3b50419fee14795c77e34, will be part of py sdk 3.0.4

**Comment by gimre-xymcity** [comment]
closed wrong one

**Comment by gimre-xymcity** [comment]
there's no V2 multisig_transaction in NEM
