### ISSUE TITLE
[client/rest] upgrade mongodb nodejs driver to 5.x

### ISSUE THREAD

**Issue by Wayonb** [symbol/symbol#619]
This is to track PR - https://github.com/symbol/symbol/pull/606

**Comment by gimre-xymcity** [comment]
@Wayonb can this be closed?

**Comment by Wayonb** [comment]
> @Wayonb can this be closed?

@gimre-xymcity This issue is to track the upgrade to mongodb 5.x requires some changes in Rest.
Currently Rest is using the  mongodb 4.14 driver https://github.com/symbol/symbol/blob/e798f62e4089b87a3036c8976369d2cb4167a515/client/rest/package.json#L33.

**Comment by Wayonb** [comment]
This is fixed in https://github.com/symbol/symbol/pull/933
