### ISSUE TITLE
[client/catapult] Conan repository URL seems broken

### ISSUE THREAD

**Issue by cowmanjoe** [symbol/symbol#790]
### System Information

- **Client Version:** 1.0.3.6
- **REST Version:** Not sure 
- **Operating System:** Linux
- **Installed With:** From Source
- **VPS Provider:** None
- **Are you fully synchronized?** No
- **Did you try to restart your node?** N/A

#### Description

I'm trying to compile the catapult client in a Docker image. I've been following the [compile with Conan guide](https://github.com/symbol/symbol/blob/dev/client/catapult/docs/BUILD-conan.md). It says to add the following URL as a remote.
```
conan remote add nemtech https://catapult.jfrog.io/artifactory/api/conan/symbol-conan
```
This URL seems to be broken as running `CONAN_REVISIONS_ENABLED=1 conan install .. --build missing` gives the error `Response from remote is not json, but 'text/html; charset=utf-8'. [Remote: nemtech]`.

When I go to this URL on browser, I can see that it returns a 302, and redirects me to https://landing.jfrog.com/reactivate-server/catapult. It looks like the server needs to be reactivated. 

#### Steps to Reproduce

> Please provide detailed steps to reproduce this bug. 
> [1.] Follow the steps [here](https://github.com/symbol/symbol/blob/dev/client/catapult/docs/BUILD-conan.md)
> [2.] Observe error on trying the `conan install` command.

**Comment by Wayonb** [comment]
Try using - ``https://conan.symbol.dev/artifactory/api/conan/catapult``

**Comment by cowmanjoe** [comment]
This worked, thank you!

**Comment by Wayonb** [comment]
Fix already merge
